import { StyleSheet } from "react-native"

export const styles = StyleSheet.create({
    container: {
        flex: 1,
        backgroundColor: "white",
    },
    header: {
        backgroundColor: "#017F56",
        paddingVertical: 30,
        paddingHorizontal: 16,
        flexDirection: "row",
        alignItems: "center",
        justifyContent: "flex-start",

        zIndex: 1,
    },
    backButton: {
        backgroundColor: "#015C40",
        width: 40,
        height: 40,
        borderRadius: 20,
        justifyContent: "center",
        alignItems: "center",
        marginRight: 10,
    },
    headerTitle: {
            color: "white",
            fontSize: 25,
            fontWeight: "bold",
            position: "absolute",
            left: 0,
            right: 0,
            textAlign: "center",

    },
    content: {
        flex: 1,
    },
    profileSection: {
        alignItems: "center",
        paddingVertical: 20,
    },
    profileImage: {
        width: 100,
        marginTop: 20,
        height: 100,
        borderRadius: 50,
        borderWidth: 3,
        borderColor: "#ffffff",
        alignSelf: "center",
    },
    profileName: {
        fontSize: 18,
        fontWeight: "bold",
        marginBottom: 10,
        marginTop: 10,
    },
    editPhotoButton: {
        backgroundColor: "#017F56",
        marginHorizontal: 20,
        marginTop: 20,
        marginBottom: 20,
        paddingVertical: 12,
        paddingHorizontal: 30,
        borderRadius: 5,
        alignItems: "center",
    },
    editPhotoText: {
        color: "white",
        fontWeight: "bold",
        fontSize: 16,
    },
    section: {
        backgroundColor: "white",
        marginHorizontal: 15,
        marginVertical: 10,
        borderRadius: 8,
        padding: 15,
    },
    sectionTitle: {
        fontSize: 16,
        fontWeight: "bold",
        marginBottom: 15,
    },
    infoRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 12,
    },
    infoLabel: {
        fontSize: 14,
        color: "#333",
    },
    infoValueContainer: {
        backgroundColor: "#f0f0f0",
        padding: 8,
        borderRadius: 5,
        flex: 1,
        marginLeft: 15,
    },
    infoValue: {
        fontSize: 14,
        color: "#555",
        padding: 4,
    },
    settingRow: {
        flexDirection: "row",
        justifyContent: "space-between",
        alignItems: "center",
        marginBottom: 15,
    },
    settingLabel: {
        fontSize: 14,
        color: "#333",
    },
    saveButton: {
        backgroundColor: "#017F56",
        marginHorizontal: 15,
        marginVertical: 20,
        paddingVertical: 12,
        borderRadius: 5,
        alignItems: "center",
    },
    saveButtonText: {
        color: "white",
        fontWeight: "bold",
        fontSize: 16,
    },
    bottomNav: {
        flexDirection: "row",
        backgroundColor: "white",
        borderTopWidth: 1,
        borderTopColor: "#e0e0e0",
        height: 60,
    },
    navItem: {
        flex: 1,
        justifyContent: "center",
        alignItems: "center",
    },
    activeNavItem: {
        borderTopWidth: 2,
        borderTopColor: "#017F56",
    },
    startGuideButton: {
        backgroundColor: "#017F56",
        marginHorizontal: 15,
        marginVertical: 10,
        paddingVertical: 12,
        borderRadius: 5,
        alignItems: "center",
    },
    startGuideButtonText: {
        color: "#fff",
        fontSize: 16,
        fontWeight: "bold",
    },
    picker: {
        height: 40,
        width: 160,
        backgroundColor: "#f0f0f0",
        borderRadius: 8,
        marginLeft: 8,
    },
})
